"""The @shinkofa/ui inventory, read from the code instead of copied by hand.

Why (measurement 2026-08-30). The Lego guard carried a hand-written list of
component names. Three numbers disagreed on the same day:

    rules/Quality.md ......... 79 components
    the package's own blurb ... 83 components
    what the code exports .... 148 components

Two thirds of the library were therefore invisible to anyone consulting the rule,
and the guard could not warn about a component it had never heard of. Measured
consequence across the workspace: 146 files redefine something the library
already ships — ThemeProvider 12 times, Skeleton and Input 8 times each.

Family: an inventory copied by hand ages and lies. So this module reads it.

Two sources, in order:
  1. the live package, when a sibling `Shinkofa-Shared` checkout is on disk —
     always current, no regeneration step to forget;
  2. a committed snapshot (`lego/ui-inventory.json`), regenerated by
     `scripts/generate-ui-inventory.py` and propagated with the methodology —
     the only source available on a propagated repo or on the VPS.

Stdlib only, cross-platform. No dependency on the shared repo being present.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

SNAPSHOT = Path(__file__).resolve().parent.parent / "lego" / "ui-inventory.json"

# The workspace layout: Kata and Shinkofa-Shared are siblings.
# This file sits at <repo>/.claude/hooks/lib/, so the workspace is 4 levels up.
DEFAULT_SHARED_ROOT = Path(__file__).resolve().parents[4] / "Shinkofa-Shared"

# `export { A, B as C } from './x'` — the braces only, so `export default` and
# `export * from` (which name nothing here) are ignored.
_EXPORT_BLOCK = re.compile(r"^\s*export\s*\{([^}]*)\}", re.MULTILINE)

# A commented-out export is not an export. Stripped before matching so a retired
# component cannot come back to life through the inventory.
_LINE_COMMENT = re.compile(r"^\s*//.*$", re.MULTILINE)
_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)

# A React component is PascalCase: an uppercase first letter and at least one
# lowercase letter after it. That excludes helpers (`cn`, `useToast`) and
# SCREAMING_CASE constants (`KI_TYPES`) without listing them one by one.
_COMPONENT_NAME = re.compile(r"^[A-Z][A-Za-z0-9]*[a-z][A-Za-z0-9]*$")


def _strip_comments(source: str) -> str:
    return _LINE_COMMENT.sub("", _BLOCK_COMMENT.sub("", source or ""))


def _public_name(specifier: str) -> str:
    """The name consumers import: whatever follows `as`, else the name itself."""
    parts = [p.strip() for p in re.split(r"\bas\b", specifier)]
    return parts[-1] if parts else ""


def exported_components(source: str) -> set[str]:
    """Every React component name a TypeScript barrel exports.

    Type-only exports are skipped: `export type { X }` for a whole block, and
    `type X` inline inside a value block. A type is not a component, and letting
    one in would make the guard warn about a name nobody can render.
    """
    names: set[str] = set()
    for block in _EXPORT_BLOCK.finditer(_strip_comments(source)):
        if re.search(r"export\s+type\s*\{", block.group(0)):
            continue
        for specifier in block.group(1).split(","):
            specifier = specifier.strip()
            if not specifier or specifier.startswith("type "):
                continue
            name = _public_name(specifier)
            if _COMPONENT_NAME.match(name):
                names.add(name)
    return names


def _read_live(shared_root: Path) -> set[str]:
    """Components exported by the checkout at `shared_root`, or an empty set."""
    src = Path(shared_root) / "packages" / "ui" / "src"
    if not src.is_dir():
        return set()
    names: set[str] = set()
    for barrel in src.rglob("index.ts"):
        try:
            names |= exported_components(barrel.read_text(encoding="utf-8"))
        except OSError:
            continue
    return names


def _read_snapshot() -> set[str]:
    try:
        data = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return set()
    return set(data.get("components") or [])


def load(shared_root: Path | None = None) -> frozenset[str]:
    """The inventory: the live package when present, else the snapshot.

    An empty or broken checkout falls back rather than returning nothing — a
    guard that silently disarms itself is worse than no guard.
    """
    root = DEFAULT_SHARED_ROOT if shared_root is None else Path(shared_root)
    return frozenset(_read_live(root) or _read_snapshot())
